language: python
python:
  - "2.6"
  - "2.7"
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --ignore E126,E127,E128,E501 ."
script:
  - python setup.py test
  - nosetests
